const users = [{
    firstName: 'firstname admin',
    name: 'name admin',
    lastName: 'lastname admin',
    roles: ['Admin'],
    email: 'jwalling@jwallingis.com',
    emailConfirm: true,
    active: true,
    id: 1,
}, {
    firstName: 'firstname admin2',
    name: 'name admin2',
    lastName: 'lastname admin2',
    roles: ['Admin'],
    email: 'jwalling@jwallingis.com 2',
    emailConfirm: true,
    active: true,
    id: 2,
}, {
    firstName: 'firstname admin',
    name: 'name admin',
    lastName: 'lastname admin',
    roles: ['Admin'],
    email: 'jwalling@jwallingis.com',
    emailConfirm: false,
    active: false,
    id: 1,
}, {
    firstName: 'firstname admin3',
    name: 'name admin3',
    lastName: 'lastname admin3',
    roles: ['Admin'],
    email: 'jwalling@jwallingis.com 3',
    emailConfirm: false,
    active: true,
    id: 3,
}, {
    firstName: 'firstname admin4',
    name: 'name admin4',
    lastName: 'lastname admin4',
    roles: ['Admin'],
    email: 'jwalling@jwallingis.com4',
    emailConfirm: true,
    active: false,
    id: 1,
}, {
    firstName: 'firstname admin5',
    name: 'name admin5',
    lastName: 'lastname admin5',
    roles: ['Admin'],
    email: 'jwalling@jwallingis.com 5',
    emailConfirm: true,
    active: true,
    id: 5,
}];

export default users;
